// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export type Domain = {
  id: string;
  domain: string;
  owner: User;
  created_at: string;
  updated_at: string | null;
};
