// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export type Mailbox = {
  id: string;
  alias: string;
  owner: User;
  domain_id: string;
  is_catch_all: boolean;
  created_at: string;
  updated_at: string | null;
};
