// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailAddress } from "./MailAddress";
import type { MailAddressList } from "./MailAddressList";

export type Mail = {
  id: string;
  message_id: string | null;
  technical_sender: string;
  from: MailAddress;
  technical_rcpt: string;
  to: MailAddressList;
  ccs: MailAddressList;
  reply_to: MailAddressList;
  headers: string | null;
  subject: string | null;
  text: string | null;
  html: string | null;
  received_at: string;
  created_at: string;
  updated_at: string | null;
};
