x-config: &shared_config
  networks:
    - shrimp_network

services:
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./apps/client/Dockerfile
  #   ports:
  #     - 80:80
  #   <<: *shared_config

  # backend:
  #   build: ./apps/server
  #   ports:
  #     - 8080:8080
  #   environment:
  #     RUST_LOG: debug
  #     DATABASE_URL: postgresql://postgres:postgres@postgres/shrimp?sslmode=disable
  #     JWT_SECRET: example_secret_that_nobody_should_know
  #   depends_on:
  #     - postgres
  #   <<: *shared_config

  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: shrimp
      POSTGRES_PASSWORD: postgres
    <<: *shared_config

  pgweb:
    image: sosedoff/pgweb
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      PGWEB_DATABASE_URL: postgresql://postgres:postgres@postgres/shrimp?sslmode=disable
    <<: *shared_config

  # ingester:
  #   build: ./packages/ingester
  #   expose:
  #     - 8047:8047
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@postgres/shrimp?sslmode=disable
  #     DEBUG: 1
  #   depends_on:
  #     - postgres
  #   <<: *shared_config

  # maddy:
  #   image: foxcpp/maddy:0.7
  #   ports:
  #     - 25:25
  #   dns:
  #     - 1.1.1.1
  #     - 8.8.8.8
  #   volumes:
  #     - ./maddy.conf:/data/maddy.conf:ro
  #   depends_on:
  #     - ingester
  #   <<: *shared_config

networks:
  shrimp_network:
    enable_ipv6: true
    ipam:
      config:
        - subnet: FC00:7368:7269:6D70::/112
