# this docker-compose file is intended to be used
# during develpoment. feel free to tinker with it.

services:
  # server:
  #   build: ./server/
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - ip6net
  #  environment:
  #    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/shrimpmail"

  postgres:
    image: postgres:16.2
    ports:
      - 5432:5432
    networks:
      - ip6net
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shrimpmail

  # maddy:
  #   image: foxcpp/maddy:0.7
  #   ports:
  #     - 25:25
  #   volumes:
  #     - ./maddy.conf:/data/maddy.conf:ro
  #   networks:
  #     - ip6net
  #   depends_on:
  #     - ingester
  #     - rspamd

  # ingester:
  #   build: ./packages/ingester
  #   networks:
  #     - ip6net
  #   expose:
  #     - 8047:8047
  # rspamd:
  #   build: ./packages/rspamd
  #   networks:
  #     - ip6net
  #   expose:
  #     - 11333:11333

networks:
   ip6net:
     enable_ipv6: true
     ipam:
       config:
         - subnet: 2001:0DB1::/112
