services:
  server:
    build: ./server/
    ports:
      - 8080:8080
    networks:
      - ip6net

  maddy:
    image: foxcpp/maddy:0.7
    ports:
      - 25:25
    volumes:
      - ./maddy.conf:/data/maddy.conf:ro
    networks:
      - ip6net
    depends_on:
      - ingester
      - rspamd

  ingester:
    build: ./ingester
    networks:
      - ip6net
    expose:
      - 8047:8047
  rspamd:
    build: ./rspamd
    networks:
      - ip6net
    expose:
      - 11333:11333

networks:
   ip6net:
     enable_ipv6: true
     ipam:
       config:
         - subnet: 2001:0DB1::/112
