[package]
name = "shrimp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.5", features = ["macros"] }
sqlx = { version = "0.8.0", features = ["runtime-tokio-rustls", "postgres", "uuid", "time"] }
tokio = { version = "1.39.2", features = ["rt-multi-thread", "macros"] }

tracing = "0.1.40"
tracing-subscriber = "0.3.18"

chrono = { version = "0.4.38", features = ["serde"] }
tower-http = { version = "0.5.2", features = ["trace"] }
dotenvy = "0.15.7"
anyhow = "1.0.86"
thiserror = "1.0.63"
serde = "1.0.204"
validator = { version = "0.18.1", features = ["derive"] }
