user  nginx;
worker_processes  auto;

events {
  worker_connections  1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  sendfile        on;
  tcp_nopush     on;

  keepalive_timeout  65;
  gzip  on;

  server {
    listen 80;
    listen [::]:80;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;

    # redirect from / to /inbox
    rewrite ^/$ /inbox permanent;

    # headers
    add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline';";

    add_header X-Frame-Options "DENY";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "no-referrer";
    add_header X-Robots-Tag "noindex, nofollow";

    error_page 404 /404.html;
    location / {
      if ($request_uri ~ ^/(.*)\.html(\?|$)) {
        return 302 /$1;
      }

      try_files $uri $uri.html $uri/ =404;
    }

    location /api {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      rewrite ^/api/?(.*)$ /$1 break;

      set $upstream backend;
      proxy_pass http://$upstream:8080;
    }
  }
}
